# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 15:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(db_index=True, null=True, srid=4326)),
                ('number_of_vehicles', models.SmallIntegerField()),
                ('number_of_casualties', models.SmallIntegerField()),
                ('date', models.DateField(db_index=True)),
                ('date_and_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('police_attended', models.BooleanField()),
                ('speed_limit', models.SmallIntegerField(blank=True, null=True)),
                ('road_1_number', models.SmallIntegerField(blank=True, null=True)),
                ('road_1', models.CharField(max_length=10)),
                ('road_2_number', models.SmallIntegerField(blank=True, null=True)),
                ('road_2', models.CharField(blank=True, max_length=10)),
                ('solar_elevation', models.FloatField(blank=True, null=True)),
                ('moon_phase', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarriagewayHazards',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HighwayAuthority',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JunctionControl',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JunctionDetail',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LightConditions',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PedestrianCrossingHuman',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PedestrianCrossingPhysical',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoliceForce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(db_index=True)),
                ('label', models.TextField()),
                ('comment', models.TextField()),
                ('homepage', models.TextField()),
                ('logo_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoadClass',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoadSurface',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoadType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialConditions',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UrbanRural',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accident',
            name='carriageway_hazards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.CarriagewayHazards'),
        ),
        migrations.AddField(
            model_name='accident',
            name='highway_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.HighwayAuthority'),
        ),
        migrations.AddField(
            model_name='accident',
            name='junction_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.JunctionControl'),
        ),
        migrations.AddField(
            model_name='accident',
            name='junction_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.JunctionDetail'),
        ),
        migrations.AddField(
            model_name='accident',
            name='light_conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.LightConditions'),
        ),
        migrations.AddField(
            model_name='accident',
            name='pedestrian_crossing_human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.PedestrianCrossingHuman'),
        ),
        migrations.AddField(
            model_name='accident',
            name='pedestrian_crossing_physical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.PedestrianCrossingPhysical'),
        ),
        migrations.AddField(
            model_name='accident',
            name='police_force',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.PoliceForce'),
        ),
        migrations.AddField(
            model_name='accident',
            name='road_1_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents_1', to='icw.RoadClass'),
        ),
        migrations.AddField(
            model_name='accident',
            name='road_2_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accidents_2', to='icw.RoadClass'),
        ),
        migrations.AddField(
            model_name='accident',
            name='road_surface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.RoadSurface'),
        ),
        migrations.AddField(
            model_name='accident',
            name='road_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.RoadType'),
        ),
        migrations.AddField(
            model_name='accident',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.Severity'),
        ),
        migrations.AddField(
            model_name='accident',
            name='special_conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.SpecialConditions'),
        ),
        migrations.AddField(
            model_name='accident',
            name='urban_rural',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.UrbanRural'),
        ),
        migrations.AddField(
            model_name='accident',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.Weather'),
        ),
    ]
