# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0002_ageband_casualtyclass_casualtyseverity_firstpointofimpact_hitobjectincarriageway_hitobjectoffcarriag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ageband',
            name='gte',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ageband',
            name='lt',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casualtyseverity',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
