# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0004_auto_20170918_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeforce',
            name='dbpedia',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='class_driver',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='class_passenger',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='font_awesome',
            field=models.CharField(max_length=30),
        ),
    ]
