# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0005_auto_20170918_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='JunctionLocation',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ageband',
            name='gte',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ageband',
            name='lt',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
