# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0006_auto_20170918_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='class_driver',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='class_passenger',
            field=models.CharField(max_length=40),
        ),
    ]
