# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0007_auto_20170918_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ageband',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='carriagewayhazards',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='casualtyclass',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='casualtyseverity',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='firstpointofimpact',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='highwayauthority',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='hitobjectincarriageway',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='hitobjectoffcarriageway',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='junctioncontrol',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='junctiondetail',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='junctionlocation',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='lightconditions',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='pedestriancrossinghuman',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='pedestriancrossingphysical',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='pedestrianlocation',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='pedestrianmovement',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='roadclass',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='roadsurface',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='roadtype',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='severity',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='skiddingandoverturning',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='specialconditions',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='towingandarticulation',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='urbanrural',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='vehicleleavingcarriageway',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='vehiclelocation',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='vehiclemanoeuvre',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='accident',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.CasualtySeverity'),
        ),
    ]
