# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0008_auto_20170918_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casualty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_ref', models.PositiveIntegerField()),
                ('casualty_ref', models.PositiveIntegerField()),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_ref', models.SmallIntegerField()),
                ('driver_age', models.SmallIntegerField(blank=True, null=True)),
                ('age_of_vehicle', models.SmallIntegerField(null=True)),
                ('engine_capacity', models.IntegerField(null=True)),
                ('make', models.TextField(blank=True)),
                ('model', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accident',
            name='road_surface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.RoadSurface'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.Accident'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_age_band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.AgeBand'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.Sex'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='first_point_of_impact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.FirstPointOfImpact'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='hit_object_in_carriageway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.HitObjectInCarriageway'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='hit_object_off_carriageway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.HitObjectOffCarriageway'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='junction_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.JunctionLocation'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='leaving_carriageway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.VehicleLeavingCarriageway'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.VehicleLocation'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manoeuvre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.VehicleManoeuvre'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='skidding_and_overturning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.SkiddingAndOverturning'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='towing_and_articulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.TowingAndArticulation'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.VehicleType'),
        ),
        migrations.AddField(
            model_name='casualty',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.Accident'),
        ),
        migrations.AddField(
            model_name='casualty',
            name='age_band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.AgeBand'),
        ),
        migrations.AddField(
            model_name='casualty',
            name='casuality_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.CasualtyClass'),
        ),
        migrations.AddField(
            model_name='casualty',
            name='pedestrian_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.PedestrianLocation'),
        ),
        migrations.AddField(
            model_name='casualty',
            name='pedestrian_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.PedestrianMovement'),
        ),
        migrations.AddField(
            model_name='casualty',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.CasualtySeverity'),
        ),
        migrations.AddField(
            model_name='casualty',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.Sex'),
        ),
        migrations.AddField(
            model_name='casualty',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.VehicleType'),
        ),
        migrations.AddField(
            model_name='casualty',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.Vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set([('accident', 'vehicle_ref')]),
        ),
        migrations.AlterUniqueTogether(
            name='casualty',
            unique_together=set([('accident', 'vehicle_ref', 'casualty_ref')]),
        ),
    ]
