# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0011_auto_20170919_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policeforce',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver_age_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.AgeBand'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver_sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.Sex'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='first_point_of_impact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.FirstPointOfImpact'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='hit_object_in_carriageway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.HitObjectInCarriageway'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='hit_object_off_carriageway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.HitObjectOffCarriageway'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='junction_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.JunctionLocation'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='leaving_carriageway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.VehicleLeavingCarriageway'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.VehicleLocation'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manoeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.VehicleManoeuvre'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='skidding_and_overturning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.SkiddingAndOverturning'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='towing_and_articulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.TowingAndArticulation'),
        ),
    ]
