# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0012_auto_20170919_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casualty',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casualties', to='icw.Accident'),
        ),
        migrations.AlterField(
            model_name='casualty',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casualties', to='icw.Vehicle'),
        ),
        migrations.AlterField(
            model_name='policeforce',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='policeforce',
            name='label',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='icw.Accident'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.VehicleType'),
        ),
    ]
