# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0013_auto_20170919_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casualty',
            old_name='casuality_class',
            new_name='casualty_class',
        ),
    ]
