# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0016_auto_20170919_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casualtydistribution',
            name='distribution',
            field=models.TextField(unique=True),
        ),
    ]
