# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0018_auto_20170919_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='character',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
