# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0019_vehicletype_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='character',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='font_awesome',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
