# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0022_auto_20170923_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citation',
            name='status',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='accidentannotation',
            name='accident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_annotation', to='icw.Accident'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='href',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
