# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0023_auto_20170923_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='href',
            field=models.URLField(max_length=1024, verbose_name='URL'),
        ),
    ]
