# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0025_auto_20170923_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentannotation',
            name='citations',
        ),
        migrations.AddField(
            model_name='citation',
            name='annotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='icw.AccidentAnnotation'),
            preserve_default=False,
        ),
    ]
