# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0026_auto_20170923_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ('published', 'created')},
        ),
        migrations.AddField(
            model_name='accident',
            name='citations',
            field=models.BooleanField(default=False),
        ),
    ]
