# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0027_auto_20170924_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='citations',
            field=models.BooleanField(db_index=True, default=False, verbose_name='References?'),
        ),
    ]
