# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def citation_to_accident(apps, schema_editor):
    Citation = apps.get_model('icw', 'Citation')
    for citation in Citation.objects.all():
        citation.accident_id = citation.annotation.accident_id
        citation.save()


def citation_from_accident(apps, schema_editor):
    Citation = apps.get_model('icw', 'Citation')
    for citation in Citation.objects.all():
        citation.annotation_id = citation.accident.annotation.id
        citation.save()



class Migration(migrations.Migration):
    dependencies = [
        ('icw', '0028_auto_20170924_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='citations',
            new_name='has_citations',
        ),
        migrations.AddField(
            model_name='citation',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='icw.Accident', null=True, blank=True),
            preserve_default=False,
        ),
        migrations.RunPython(citation_to_accident, citation_from_accident),
        migrations.RemoveField(
            model_name='citation',
            name='annotation',
        ),
        migrations.AlterField(
            model_name='citation',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='icw.Accident'),
        ),
    ]
