# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icw', '0029_citation_to_accident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, unique=True)),
                ('label', models.TextField(blank=True)),
                ('data_error', models.PositiveSmallIntegerField(choices=[(0, 'no'), (1, 'possible'), (2, 'likely'), (3, 'definite')], default=0)),
                ('automated', models.BooleanField(default=False)),
                ('methodology', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.Accident')),
                ('casualty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.Casualty')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icw.Tag')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icw.Vehicle')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='accidents',
            field=models.ManyToManyField(blank=True, related_name='tags', through='icw.Tagging', to='icw.Accident'),
        ),
        migrations.AddField(
            model_name='tag',
            name='casualties',
            field=models.ManyToManyField(blank=True, related_name='tags', through='icw.Tagging', to='icw.Casualty'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagging',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='tags', through='icw.Tagging', to='icw.Vehicle'),
        ),
    ]
