# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_pedestrian_hit_by(apps, schema_editor):
    Casualty = apps.get_model('icw', 'Casualty')
    for casualty in Casualty.objects.filter(type_id=0).select_related('vehicle'):
        casualty.pedestrian_hit_by_id = casualty.vehicle.type_id
        casualty.save(force_update=True)


def remove_pedestrian_hit_by(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0030_casualty_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='casualty',
            name='pedestrian_hit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hit_pedestrians', to='icw.VehicleType'),
        ),
        migrations.RunPython(
            add_pedestrian_hit_by, remove_pedestrian_hit_by
        )
    ]

