# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 08:22
from __future__ import unicode_literals

from django.db import migrations


def prune_duplicates(apps, schema_editor):
    Citation = apps.get_model('icw', 'Citation')
    seen = set()
    for citation in Citation.objects.order_by('created'):
        key = (citation.accident_id, citation.href)
        if key in seen:
            citation.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0031_casualty_pedestrian_hit_by'),
    ]

    operations = [
        migrations.RunPython(
            prune_duplicates,
            lambda apps, schema_editor: None,
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together=set([('accident', 'href')]),
        ),
    ]
