# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0035_highwayauthority_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='highwayauthority',
            name='mapit_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
