# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 22:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0036_highwayauthority_mapit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeforce',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_index=True, null=True, srid=4326),
        ),
    ]
