# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icw', '0039_auto_20171228_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='police_attended',
            field=models.NullBooleanField(),
        ),
    ]
